"use strict";
// Copyright (C) 2025 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
Object.defineProperty(exports, "__esModule", { value: true });
exports.language = void 0;
exports.perfettoSql = perfettoSql;
exports.parseAndPrintTree = parseAndPrintTree;
const language_1 = require("@codemirror/language");
const highlight_1 = require("@lezer/highlight");
const perfetto_sql_grammar_1 = require("./perfetto_sql.grammar"); // Generated by Lezer
exports.language = language_1.LRLanguage.define({
    parser: perfetto_sql_grammar_1.parser.configure({
        props: [
            language_1.indentNodeProp.add({
                Application: (0, language_1.delimitedIndent)({ closing: ')', align: false }),
            }),
            language_1.foldNodeProp.add({
                Application: language_1.foldInside,
            }),
            (0, highlight_1.styleTags)({
                'Keyword': highlight_1.tags.keyword,
                'Boolean': highlight_1.tags.bool,
                'Null': highlight_1.tags.null,
                'String': highlight_1.tags.string,
                'Number': highlight_1.tags.number,
                'LineComment': highlight_1.tags.lineComment,
                'Macro': highlight_1.tags.macroName,
                'MacroVariable': highlight_1.tags.variableName,
                'Function': highlight_1.tags.function(highlight_1.tags.variableName),
                '( )': highlight_1.tags.paren,
            }),
        ],
    }),
    languageData: {
        commentTokens: { line: '--' },
    },
});
function perfettoSql() {
    return new language_1.LanguageSupport(exports.language);
}
function parseAndPrintTree(code) {
    const tree = exports.language.parser.parse(code);
    const cursor = tree.cursor();
    printCST(cursor, code);
}
// Helper function to pretty-print the CST
function printCST(cursor, source, indent = 0) {
    const nodeName = cursor.name;
    const nodeText = source.substring(cursor.from, cursor.to);
    console.log(`${'  '.repeat(indent)}${nodeName}: "${nodeText}"`);
    if (cursor.firstChild()) {
        do {
            printCST(cursor, source, indent + 1);
        } while (cursor.nextSibling());
        cursor.parent(); // Important: Move back up to the parent
    }
}
//# sourceMappingURL=language.js.map