"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MacroVariable = exports.Function = exports.Keyword = exports.Null = exports.Identifier = exports.Boolean = exports.Number = exports.String = exports.Program = exports.LineComment = void 0;
// This file was generated by lezer-generator. You probably shouldn't edit it.
exports.LineComment = 1, exports.Program = 2, exports.String = 3, exports.Number = 4, exports.Boolean = 5, exports.Identifier = 6, exports.Null = 7, exports.Keyword = 8, exports.Function = 9, exports.MacroVariable = 10;
//# sourceMappingURL=perfetto_sql.grammar.terms.js.map