"use strict";
// Copyright (C) 2024 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
Object.defineProperty(exports, "__esModule", { value: true });
exports.WattsonProcessSelectionAggregator = void 0;
const utils_1 = require("../../base/utils");
const track_kinds_1 = require("../../public/track_kinds");
const aggregation_panel_1 = require("./aggregation_panel");
class WattsonProcessSelectionAggregator {
    id = 'wattson_plugin_process_aggregation';
    Panel = aggregation_panel_1.WattsonAggregationPanel;
    probe(area) {
        const selectedCpus = [];
        for (const trackInfo of area.tracks) {
            trackInfo?.tags?.kind === track_kinds_1.CPU_SLICE_TRACK_KIND &&
                (0, utils_1.exists)(trackInfo.tags.cpu) &&
                selectedCpus.push(trackInfo.tags.cpu);
        }
        if (selectedCpus.length === 0)
            return undefined;
        return {
            prepareData: async (engine) => {
                await engine.query(`drop view if exists ${this.id};`);
                const duration = area.end - area.start;
                // Prerequisite tables are already generated by Wattson thread aggregation,
                // which is run prior to execution of this module
                await engine.query(`
          INCLUDE PERFETTO MODULE wattson.estimates;
          INCLUDE PERFETTO MODULE wattson.tasks.idle_transitions_attribution;

          -- Group idle attribution by process
          CREATE OR REPLACE PERFETTO TABLE
          wattson_plugin_per_process_idle_attribution AS
          SELECT
            SUM(idle_cost_mws) as idle_cost_mws,
            upid
          FROM wattson_plugin_idle_attribution
          GROUP BY upid;

          -- Grouped by UPID and made CPU agnostic
          CREATE PERFETTO VIEW ${this.id} AS
          WITH base AS (
            SELECT
              ROUND(SUM(total_pws) / ${duration}, 3) as active_mw,
              ROUND(SUM(total_pws) / 1000000000, 3) as active_mws,
              ROUND(COALESCE(idle_cost_mws, 0), 3) as idle_cost_mws,
              ROUND(
                COALESCE(idle_cost_mws, 0) + SUM(total_pws) / 1000000000,
                3
              ) as total_mws,
              pid,
              process_name
            FROM wattson_plugin_unioned_per_cpu_total
            LEFT JOIN wattson_plugin_per_process_idle_attribution USING (upid)
            GROUP BY upid
          ),
          secondary AS (
            SELECT
              pid,
              total_mws / (SUM(total_mws) OVER()) AS percent_of_total_energy
            FROM base
            GROUP BY pid
          )
          select *
            from base INNER JOIN secondary
            USING (pid);
        `);
                return {
                    tableName: this.id,
                };
            },
        };
    }
    getColumnDefinitions() {
        return [
            {
                title: 'Process Name',
                columnId: 'process_name',
            },
            {
                title: 'PID',
                columnId: 'pid',
            },
            {
                title: 'Active power (estimated mW)',
                columnId: 'active_mw',
                sum: true,
            },
            {
                title: 'Active energy (estimated mWs)',
                columnId: 'active_mws',
                sum: true,
            },
            {
                title: 'Idle transitions overhead (estimated mWs)',
                columnId: 'idle_cost_mws',
                sum: false,
            },
            {
                title: 'Total energy (estimated mWs)',
                columnId: 'total_mws',
                sum: true,
            },
            {
                title: '% of total energy',
                formatHint: 'PERCENT',
                columnId: 'percent_of_total_energy',
                sum: false,
            },
        ];
    }
    getTabName() {
        return 'Wattson by process';
    }
    getDefaultSorting() {
        return { column: 'active_mws', direction: 'DESC' };
    }
}
exports.WattsonProcessSelectionAggregator = WattsonProcessSelectionAggregator;
//# sourceMappingURL=process_aggregator.js.map