"use strict";
// Copyright (C) 2024 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
Object.defineProperty(exports, "__esModule", { value: true });
exports.traceConfigToTxt = traceConfigToTxt;
exports.traceConfigToPb = traceConfigToPb;
const tslib_1 = require("tslib");
const protos_1 = tslib_1.__importDefault(require("../../../protos"));
const assets_1 = require("../../../base/assets");
const deferred_1 = require("../../../base/deferred");
const logging_1 = require("../../../base/logging");
const result_1 = require("../../../base/result");
const string_utils_1 = require("../../../base/string_utils");
const trace_config_utils_1 = tslib_1.__importDefault(require("../../../gen/trace_config_utils"));
let moduleInstance = undefined;
/**
 * Convert a binary-encoded protos.TracConfig to pbtxt (i.e. the text format
 * that can be passed to perfetto --txt).
 */
async function traceConfigToTxt(config) {
    const wasm = await initWasmOnce();
    const configU8 = config instanceof Uint8Array
        ? config
        : protos_1.default.TraceConfig.encode(config).finish();
    (0, logging_1.assertTrue)(configU8.length <= wasm.buf.length);
    wasm.buf.set(configU8);
    const txtSize = wasm.module.ccall('trace_config_pb_to_txt', 'number', ['number'], [configU8.length]) >>> 0;
    const txt = (0, string_utils_1.utf8Decode)(wasm.buf.subarray(0, txtSize));
    return txt;
}
/** Convert a pbtxt (text-proto) text to a proto-encoded TraceConfig. */
async function traceConfigToPb(configTxt) {
    const wasm = await initWasmOnce();
    const configUtf8 = (0, string_utils_1.utf8Encode)(configTxt);
    (0, logging_1.assertTrue)(configUtf8.length <= wasm.buf.length);
    wasm.buf.set(configUtf8);
    const resSize = wasm.module.ccall('trace_config_txt_to_pb', 'number', ['number'], [configUtf8.length]) >>> 0;
    const success = wasm.buf.at(0) === 1;
    const payload = wasm.buf.slice(1, 1 + resSize);
    return success ? (0, result_1.okResult)(payload) : (0, result_1.errResult)((0, string_utils_1.utf8Decode)(payload));
}
async function initWasmOnce() {
    if (moduleInstance === undefined) {
        // We have to fetch the .wasm file manually because the stub generated by
        // emscripten uses sync-loading, which works only in Workers.
        const resp = await fetch((0, assets_1.assetSrc)('trace_config_utils.wasm'));
        const wasmBinary = await resp.arrayBuffer();
        const deferredRuntimeInitialized = (0, deferred_1.defer)();
        const instance = (0, trace_config_utils_1.default)({
            noInitialRun: true,
            locateFile: (s) => s,
            print: (s) => console.log(s),
            printErr: (s) => console.error(s),
            onRuntimeInitialized: () => deferredRuntimeInitialized.resolve(),
            wasmBinary,
        });
        await deferredRuntimeInitialized;
        const bufAddr = instance.ccall('trace_config_utils_buf', 'number', [], []) >>> 0;
        const bufSize = instance.ccall('trace_config_utils_buf_size', 'number', [], []) >>> 0;
        moduleInstance = {
            module: instance,
            buf: instance.HEAPU8.subarray(bufAddr, bufAddr + bufSize),
        };
    }
    return moduleInstance;
}
//# sourceMappingURL=trace_config_utils_wasm.js.map